// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-micro-template/config"
	"go-micro-template/internal/biz"
	"go-micro-template/internal/data"
	"go-micro-template/internal/service"
	"go-micro-template/internal/socialconfig"
	"go-micro-template/pkg/app"
	"go-micro-template/pkg/logger"
	"go-micro-template/pkg/tracing"
)

import (
	_ "dubbo.apache.org/dubbo-go/v3/filter/tps/strategy"
	_ "dubbo.apache.org/dubbo-go/v3/imports"
	_ "go-micro-template/internal/handler"
)

// Injectors from wire.go:

func InitApp() (*app.App, error) {
	appConfig := config.NewConfig()
	provider := socialconfig.NewSocialConfigProvider(appConfig)
	zapLogger := logger.NewZap(appConfig)
	dataData := data.NewData(appConfig)
	mediaAccountRepo := data.NewMediaAccountRepo(dataData)
	workRepo := data.NewWorkRepo(dataData)
	workImageRepo := data.NewWorkImageRepo(dataData)
	workVideoRepo := data.NewWorkVideoRepo(dataData)
	workLogRepo := data.NewWorkLogRepo(dataData)
	costLogRepo := data.NewCostLogRepo(dataData)
	bundleOrderRecordsRepo := data.NewBundleOrderRecordsRepo(dataData)
	castUseCase := biz.NewCastUseCase(mediaAccountRepo, workRepo, workImageRepo, workVideoRepo, workLogRepo, costLogRepo, bundleOrderRecordsRepo)
	youTubeUseCase := biz.NewYouTubeUseCase(provider, appConfig)
	useCase := biz.NewUseCase(castUseCase, youTubeUseCase)
	castService := service.NewCastService(castUseCase, youTubeUseCase)
	jaegerProvider := tracing.NewTracing()
	appApp := NewApp(appConfig, provider, zapLogger, useCase, dataData, castService, jaegerProvider)
	return appApp, nil
}
